@extends ('layout')

@section ('header')

<div id="header-featured">
    <div id="banner-wrapper">
        <div id="banner" class="container">
            <h2>Welcome to this website!</h2>
            <p>This is just a short sample website generated by following the Laracast tutorial.
                I was just interested in learning some Laravel for my job, and want to gain more experience with PHP.</p>
            <a href="#" class="button">Better website</a>
        </div>
    </div>
</div>

@endsection


@section ('content')

@endsection